//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Board
    {
        public Board()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public System.Guid Id { get; set; }
        public string ShortName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
