//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid VideoId { get; set; }
        public System.Guid ThreadId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
        public virtual Thread Thread { get; set; }
    }
}
