//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment : IEntity
    {
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid VideoId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Video Video { get; set; }
    }
}
