//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Threads = new HashSet<Thread>();
        }
    
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public byte[] PasswordHash { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
