//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class User : IEntity
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public byte[] PasswordHash { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
