//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Threads = new HashSet<Thread>();
        }
    
        public System.Guid Id { get; set; }
        public string Login { get; set; }
        public byte[] PasswordHash { get; set; }
    
        public virtual ICollection<Thread> Threads { get; set; }
    }
}
